library:
    bing:
        path: path/to/Bing
        pretain_last_images: 1000
        suffix: png
    ng:
        path: path/to/NG
        pretain_last_images: 1000
        suffix: png

image_source: bing
model_file:
    X2:
        ../models/latest_x2.pth
        #../models/latest_x2.onnx
set_wallpaper: True